import type { TraceSpan } from "@/components/trace-view";

export const mockTraceSpans: TraceSpan[] = [
  {
    id: "root",
    name: "root.run",
    startMs: 0,
    durationMs: 1420,
    status: "success",
    prompt: "Handle user request and produce final response",
    response: "Run completed with one tool failure recovered",
    tokens: 804,
    latencyMs: 1420,
  },
  {
    id: "plan",
    parentId: "root",
    name: "planner.step",
    startMs: 90,
    durationMs: 360,
    status: "success",
    prompt: "Break the task into retrieval and synthesis steps",
    response: "Plan: retrieve docs, rank snippets, synthesize answer",
    tokens: 146,
    latencyMs: 360,
  },
  {
    id: "tool-search",
    parentId: "root",
    name: "tool.search_docs",
    startMs: 470,
    durationMs: 420,
    status: "success",
    prompt: "Query internal docs for billing timeout handling",
    response: "Fetched 5 candidate docs",
    tokens: 98,
    latencyMs: 420,
  },
  {
    id: "tool-ranker",
    parentId: "tool-search",
    name: "tool.rank_results",
    startMs: 620,
    durationMs: 180,
    status: "running",
    prompt: "Rank retrieved docs by relevance to current incident",
    response: "Top-2 ranked, waiting on model completion",
    tokens: 62,
    latencyMs: 180,
  },
  {
    id: "tool-email",
    parentId: "root",
    name: "tool.send_email",
    startMs: 910,
    durationMs: 210,
    status: "error",
    prompt: "Send failure summary to oncall@company.com",
    response: "EmailServiceError: Missing API key",
    tokens: 34,
    latencyMs: 210,
    rca: {
      summary: "Email delivery step failed before external API request was accepted.",
      rootCause: "SMTP provider key was not configured in runtime secrets for this environment.",
      location: "tool.send_email -> EmailClient.send()",
      suggestedFix: "Add EMAIL_API_KEY to deployment secrets and guard this step with fallback notification channel.",
      confidence: 0.93,
    },
  },
  {
    id: "finalize",
    parentId: "root",
    name: "llm.final_answer",
    startMs: 1140,
    durationMs: 240,
    status: "success",
    prompt: "Generate concise remediation summary for user",
    response: "Provided fallback response and remediation step",
    tokens: 274,
    latencyMs: 240,
  },
];
