ALTER TABLE run_insights
ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS cause TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS impact TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS fix JSONB NOT NULL DEFAULT '[]'::jsonb;
